# Array Creation

[![Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/chaobrain/saiunit/blob/master/docs/mathematical_functions/array_creation.ipynb)
[![Open in Kaggle](https://kaggle.com/static/images/open-in-kaggle.svg)](https://kaggle.com/kernels/welcome?src=https://github.com/chaobrain/saiunit/blob/master/docs/mathematical_functions/array_creation.ipynb)

The functions listed below are designed to create `array` or `Quantity` with specific properties, such as filled with a certain value, identity matrices, or arrays with ones on the diagonal. These functions are part of the `saiunit.math` module and are tailored to handle both numerical `array` and `Quantity` with units.

In [1]:
import saiunit as u
import jax.numpy as jnp

## `saiunit.math.array` & `saiunit.math.asarray`

Convert the input to a quantity or array.

  If unit is provided, the input will be checked whether it has the same unit as the provided unit.
  (If they have same dimension but different magnitude, the input will be converted to the provided unit.)
  If unit is not provided, the input will be converted to an array.

In [2]:
u.math.asarray([1, 2, 3])                       # return a jax.Array

Array([1, 2, 3], dtype=int32)

In [3]:
u.math.asarray([1, 2, 3], unit=u.second)    # return a Quantity

Array([1, 2, 3], dtype=int32)

In [4]:
# check if the input has the same unit as the provided unit
u.math.asarray([1 * u.second, 2 * u.second], unit=u.second)

Quantity([1 2], "s")

In [5]:
# fails because the input has a different unit
try:
    u.math.asarray([1 * u.second, 2 * u.second], unit=u.ampere)
except Exception as e:
    print(e)

Cannot convert to a unit with different dimensions. (units are s and A).


## `saiunit.math.arange`
Return evenly spaced values within a given interval.

In [6]:
u.math.arange(5)                                    # return a jax.Array

Array([0, 1, 2, 3, 4], dtype=int32)

In [7]:
u.math.arange(5 * u.second, step=1 * u.second) # return a Quantity

Quantity([0 1 2 3 4], "s")

In [8]:
u.math.arange(3, 9, 1)                                          # return a jax.Array

Array([3, 4, 5, 6, 7, 8], dtype=int32)

In [9]:
u.math.arange(3 * u.second, 9 * u.second, 1 * u.second)   # return a Quantity

Quantity([3 4 5 6 7 8], "s")

## `saiunit.math.array_split`
Split an array into multiple sub-arrays.

In [10]:
a = jnp.arange(9)

u.math.array_split(a, 3)      # return a jax.Array

[Array([0, 1, 2], dtype=int32),
 Array([3, 4, 5], dtype=int32),
 Array([6, 7, 8], dtype=int32)]

In [11]:
q = jnp.arange(9) * u.second

u.math.array_split(q, 3)   # return a Quantity

[Quantity([0 1 2], "s"), Quantity([3 4 5], "s"), Quantity([6 7 8], "s")]

## `saiunit.math.linspace`
Return evenly spaced numbers over a specified interval.

In [12]:
u.math.linspace(0, 10, 5)                               # return a jax.Array

Array([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32)

In [13]:
u.math.linspace(0 * u.second, 10 * u.second, 5)    # return a Quantity

Quantity([ 0.   2.5  5.   7.5 10. ], "s")

## `saiunit.math.logspace`
Return numbers spaced evenly on a log scale.

In [14]:
u.math.logspace(0, 10, 5)                               # return a jax.Array

Array([1.0000000e+00, 3.1622775e+02, 1.0000000e+05, 3.1622776e+07,
       1.0000000e+10], dtype=float32)

In [15]:
u.math.logspace(0 * u.second, 10 * u.second, 5)    # return a Quantity

Quantity([1.0000000e+00 3.1622775e+02 1.0000000e+05 3.1622776e+07 1.0000000e+10], "s")

## `saiunit.math.meshgrid`
Return coordinate matrices from coordinate vectors.

In [16]:
x = jnp.array([1, 2, 3])
y = jnp.array([4, 5])

u.math.meshgrid(x, y)           # return a jax.Array

[Array([[1, 2, 3],
        [1, 2, 3]], dtype=int32),
 Array([[4, 4, 4],
        [5, 5, 5]], dtype=int32)]

In [17]:
x_q = jnp.array([1, 2, 3]) * u.second
y_q = jnp.array([4, 5]) * u.second

u.math.meshgrid(x_q, y_q)    # return a Quantity

[Quantity([[1 2 3]
           [1 2 3]], "s"),
 Quantity([[4 4 4]
           [5 5 5]], "s")]

## `saiunit.math.vander`
Generate a Vandermonde matrix.

The Vandermonde matrix is a matrix with the terms of a geometric progression in each row.
  The geometric progression is defined by the vector `x` and the number of columns `N`.


In [18]:
a = jnp.array([1, 2, 3])

u.math.vander(a)                       # return a jax.Array

Array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]], dtype=int32)

## Can use with `Quantity`

The functions below can be used with `Quantity` with units.

### `saiunit.math.full`
Returns a quantity or array filled with a specific value.

In [19]:
u.math.full(3, 4)                   # return a jax.Array

Array([4, 4, 4], dtype=int32, weak_type=True)

In [20]:
u.math.full(3, 4 * u.second)    # return a Quantity

Quantity([4 4 4], "s")

### `saiunit.math.empty`
Return a new quantity or array of given shape and type, without initializing entries.

In [21]:
u.math.empty((2, 2))                    # return a jax.Array

Array([[0., 0.],
       [0., 0.]], dtype=float32)

In [22]:
u.math.empty((2, 2), unit=u.second) # return a Quantity

Quantity([[0. 0.]
          [0. 0.]], "s")

### `saiunit.math.ones`
Returns a new quantity or array of given shape and type, filled with ones.

In [23]:
u.math.ones((2, 2))                     # return a jax.Array

Array([[1., 1.],
       [1., 1.]], dtype=float32)

In [24]:
u.math.ones((2, 2), unit=u.second)  # return a Quantity

Quantity([[1. 1.]
          [1. 1.]], "s")

### `saiunit.math.zeros`
Returns a new quantity or array of given shape and type, filled with ones.

In [25]:
u.math.zeros((2, 2))                    # return a jax.Array

Array([[0., 0.],
       [0., 0.]], dtype=float32)

In [26]:
u.math.zeros((2, 2), unit=u.second) # return a Quantity

Quantity([[0. 0.]
          [0. 0.]], "s")

### `saiunit.math.full_like`
Return a new quantity or array with the same shape and type as a given array or quantity, filled with `fill_value`.


In [27]:
a = jnp.array([1, 2, 3])

u.math.full_like(a, 4)                       # return a jax.Array

Array([4, 4, 4], dtype=int32)

In [28]:
try:
    u.math.full_like(a, 4 * u.second)         # return a Quantity
except Exception as e:
    print(e)

full_like requires "fill_value" to be dimensionless when "a" is a plain array, but got fill_value with unit=s. Either pass a plain number as fill_value or wrap "a" as a Quantity.


### `saiunit.math.empty_like`
Return a new quantity or array with the same shape and type as a given array.


In [29]:
a = jnp.array([1, 2, 3])

u.math.empty_like(a)       # return a jax.Array

Array([0, 0, 0], dtype=int32)

In [30]:
q = jnp.array([1, 2, 3]) * u.second

u.math.empty_like(q)    # return a Quantity

Quantity([0 0 0], "s")

### `saiunit.math.ones_like`
Return a new quantity or array with the same shape and type as a given array, filled with ones.

In [31]:
a = jnp.array([1, 2, 3])

u.math.ones_like(a)       # return a jax.Array

Array([1, 1, 1], dtype=int32)

In [32]:
q = jnp.array([1, 2, 3]) * u.second

u.math.ones_like(q)    # return a Quantity

Quantity([1 1 1], "s")

### `saiunit.math.zeros_like`
Return a new quantity or array with the same shape and type as a given array, filled with zeros.

In [33]:
a = jnp.array([1, 2, 3])

u.math.zeros_like(a)       # return a jax.Array

Array([0, 0, 0], dtype=int32)

In [34]:
q = jnp.array([1, 2, 3]) * u.second

u.math.zeros_like(q)    # return a Quantity

Quantity([0 0 0], "s")

### `saiunit.math.fill_diagonal`
Fill the main diagonal of the given array of any dimensionality.

In [35]:
a = jnp.zeros((3, 3))

u.math.fill_diagonal(a, 4)      # return a jax.Array

Array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]], dtype=float32)

In [36]:
q = jnp.zeros((3, 3)) * u.second

u.math.fill_diagonal(q, 4 * u.second)   # return a Quantity

Quantity([[4. 0. 0.]
          [0. 4. 0.]
          [0. 0. 4.]], "s")

## Can use with `unit` keyword

The functions below can be used with the `unit` keyword.

### `saiunit.math.eye`
Returns a 2-D quantity or array with ones on the diagonal and zeros elsewhere.

In [37]:
u.math.eye(3)                       # return a jax.Array

Array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [38]:
u.math.eye(3, unit=u.second)    # return a Quantity

Quantity([[1. 0. 0.]
          [0. 1. 0.]
          [0. 0. 1.]], "s")

### `saiunit.math.identity`
Return the identity Quantity or array.

In [39]:
u.math.identity(3)                  # return a jax.Array

Array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [40]:
u.math.identity(3, unit=u.second)    # return a Quantity

Quantity([[1. 0. 0.]
          [0. 1. 0.]
          [0. 0. 1.]], "s")

### `saiunit.math.tri`
Returns A quantity or an array with ones at and below the given diagonal and zeros elsewhere.


In [41]:
u.math.tri(3)                       # return a jax.Array

Array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]], dtype=float32)

In [42]:
u.math.tri(3, unit=u.second)    # return a Quantity

Quantity([[1. 0. 0.]
          [1. 1. 0.]
          [1. 1. 1.]], "s")

### `saiunit.math.diag`
Extract a diagonal or construct a diagonal array.

In [43]:
a = jnp.array([1, 2, 3])

u.math.diag(a)                       # return a jax.Array

Array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]], dtype=int32)

In [44]:
u.math.diag(a, unit=u.second)    # return a Quantity

Quantity([[1 0 0]
          [0 2 0]
          [0 0 3]], "s")

### `saiunit.math.tril`
Lower triangle of an array.

  Return a copy of a matrix with the elements above the `k`-th diagonal zeroed.
  For quantities or arrays with ``ndim`` exceeding 2, `tril` will apply to the final two axes.


In [45]:
a = jnp.ones((3, 3))

u.math.diag(a)                       # return a jax.Array

Array([1., 1., 1.], dtype=float32)

In [46]:
u.math.diag(a, unit=u.second)    # return a Quantity

Quantity([1. 1. 1.], "s")

### `saiunit.math.triu`
Upper triangle of an array.

  Return a copy of a matrix with the elements below the `k`-th diagonal zeroed.
  For quantities or arrays with ``ndim`` exceeding 2, `triu` will apply to the final two axes.

In [47]:
a = jnp.ones((3, 3))

u.math.tril(a)                       # return a jax.Array

Array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]], dtype=float32)

In [48]:
u.math.tril(a, unit=u.second)    # return a Quantity

Quantity([[1. 0. 0.]
          [1. 1. 0.]
          [1. 1. 1.]], "s")